/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BookingInquiry {
  'checkIn' : string,
  'name' : string,
  'email' : string,
  'message' : string,
  'checkOut' : string,
  'numberOfGuests' : bigint,
}
export interface GuestReview {
  'stayDate' : string,
  'guestName' : string,
  'comment' : string,
  'rating' : bigint,
}
export interface Room {
  'pricePerNight' : bigint,
  'name' : string,
  'description' : string,
  'amenities' : Array<string>,
  'maxGuests' : bigint,
}
export interface _SERVICE {
  'addGuestReview' : ActorMethod<[string, bigint, string, string], undefined>,
  'getAllBookingInquiries' : ActorMethod<[], Array<BookingInquiry>>,
  'getAllGuestReviews' : ActorMethod<[], Array<GuestReview>>,
  'getRooms' : ActorMethod<[], Array<Room>>,
  'submitBookingInquiry' : ActorMethod<
    [string, string, string, string, bigint, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];