/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BookingInquiry = IDL.Record({
  'checkIn' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'checkOut' : IDL.Text,
  'numberOfGuests' : IDL.Nat,
});
export const GuestReview = IDL.Record({
  'stayDate' : IDL.Text,
  'guestName' : IDL.Text,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
});
export const Room = IDL.Record({
  'pricePerNight' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'amenities' : IDL.Vec(IDL.Text),
  'maxGuests' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addGuestReview' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text, IDL.Text], [], []),
  'getAllBookingInquiries' : IDL.Func([], [IDL.Vec(BookingInquiry)], ['query']),
  'getAllGuestReviews' : IDL.Func([], [IDL.Vec(GuestReview)], ['query']),
  'getRooms' : IDL.Func([], [IDL.Vec(Room)], ['query']),
  'submitBookingInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BookingInquiry = IDL.Record({
    'checkIn' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'checkOut' : IDL.Text,
    'numberOfGuests' : IDL.Nat,
  });
  const GuestReview = IDL.Record({
    'stayDate' : IDL.Text,
    'guestName' : IDL.Text,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const Room = IDL.Record({
    'pricePerNight' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'amenities' : IDL.Vec(IDL.Text),
    'maxGuests' : IDL.Nat,
  });
  
  return IDL.Service({
    'addGuestReview' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'getAllBookingInquiries' : IDL.Func(
        [],
        [IDL.Vec(BookingInquiry)],
        ['query'],
      ),
    'getAllGuestReviews' : IDL.Func([], [IDL.Vec(GuestReview)], ['query']),
    'getRooms' : IDL.Func([], [IDL.Vec(Room)], ['query']),
    'submitBookingInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };