/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent } from "@icp-sdk/core/agent";
import { idlFactory } from "./declarations/backend.did";
function some(value) {
  return {
    __kind__: "Some",
    value: value
  };
}
function none() {
  return {
    __kind__: "None"
  };
}
function isNone(option) {
  return option.__kind__ === "None";
}
function isSome(option) {
  return option.__kind__ === "Some";
}
function unwrap(option) {
  if (isNone(option)) {
    throw new Error("unwrap: none");
  }
  return option.value;
}
function candid_some(value) {
  return [value];
}
function candid_none() {
  return [];
}
function record_opt_to_undefined(arg) {
  return arg == null ? undefined : arg;
}
export class ExternalBlob {
  onProgress = undefined;
  constructor(directURL, blob) {
    if (blob) {
      this._blob = blob;
    }
    this.directURL = directURL;
  }
  static fromURL(url) {
    return new ExternalBlob(url, null);
  }
  static fromBytes(blob) {
    const url = URL.createObjectURL(new Blob([new Uint8Array(blob)], {
      type: 'application/octet-stream'
    }));
    return new ExternalBlob(url, blob);
  }
  async getBytes() {
    if (this._blob) {
      return this._blob;
    }
    const response = await fetch(this.directURL);
    const blob = await response.blob();
    this._blob = new Uint8Array(await blob.arrayBuffer());
    return this._blob;
  }
  getDirectURL() {
    return this.directURL;
  }
  withUploadProgress(onProgress) {
    this.onProgress = onProgress;
    return this;
  }
}
export class Backend {
  constructor(actor, _uploadFile, _downloadFile, processError) {
    this.actor = actor;
    this._uploadFile = _uploadFile;
    this._downloadFile = _downloadFile;
    this.processError = processError;
  }
  async addGuestReview(arg0, arg1, arg2, arg3) {
    if (this.processError) {
      try {
        const result = await this.actor.addGuestReview(arg0, arg1, arg2, arg3);
        return result;
      } catch (e) {
        this.processError(e);
        throw new Error("unreachable");
      }
    } else {
      const result = await this.actor.addGuestReview(arg0, arg1, arg2, arg3);
      return result;
    }
  }
  async getAllBookingInquiries() {
    if (this.processError) {
      try {
        const result = await this.actor.getAllBookingInquiries();
        return result;
      } catch (e) {
        this.processError(e);
        throw new Error("unreachable");
      }
    } else {
      const result = await this.actor.getAllBookingInquiries();
      return result;
    }
  }
  async getAllGuestReviews() {
    if (this.processError) {
      try {
        const result = await this.actor.getAllGuestReviews();
        return result;
      } catch (e) {
        this.processError(e);
        throw new Error("unreachable");
      }
    } else {
      const result = await this.actor.getAllGuestReviews();
      return result;
    }
  }
  async getRooms() {
    if (this.processError) {
      try {
        const result = await this.actor.getRooms();
        return result;
      } catch (e) {
        this.processError(e);
        throw new Error("unreachable");
      }
    } else {
      const result = await this.actor.getRooms();
      return result;
    }
  }
  async submitBookingInquiry(arg0, arg1, arg2, arg3, arg4, arg5) {
    if (this.processError) {
      try {
        const result = await this.actor.submitBookingInquiry(arg0, arg1, arg2, arg3, arg4, arg5);
        return result;
      } catch (e) {
        this.processError(e);
        throw new Error("unreachable");
      }
    } else {
      const result = await this.actor.submitBookingInquiry(arg0, arg1, arg2, arg3, arg4, arg5);
      return result;
    }
  }
}
export function createActor(canisterId, _uploadFile, _downloadFile, options = {}) {
  const agent = options.agent || HttpAgent.createSync({
    ...options.agentOptions
  });
  if (options.agent && options.agentOptions) {
    console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
  }
  const actor = Actor.createActor(idlFactory, {
    agent,
    canisterId: canisterId,
    ...options.actorOptions
  });
  return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}